### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by fanweiya** [ksugar/qupath-extension-cellsparse#5]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/cellsparse_api/main.py", line 144, in stardist
    return run(
           ^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/cellsparse_api/main.py", line 47, in run
    pred = runner._eval([img], modelname)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/cellsparse/runners/stardist_runner.py", line 106, in _eval
    model = StarDist2D(self.config, name=description, basedir=self.basedir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/stardist/models/model2d.py", line 296, in __init__
    super().__init__(config, name=name, basedir=basedir)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/stardist/models/base.py", line 223, in __init__
    super().__init__(config=config, name=name, basedir=basedir)
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/csbdeep/models/base_model.py", line 111, in __init__
    self.keras_model = self._build()
                       ^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/stardist/models/model2d.py", line 312, in _build
    pooled_img = Conv2D(self.config.unet_n_filter_base, self.config.unet_kernel_size,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/anaconda3/envs/cellsparse-api/lib/python3.11/site-packages/keras/backend.py", line 2101, in random_uniform
    return tf.random.stateless_uniform(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Memory growth cannot differ between GPU devices

**Comment by ksugar** [comment]
Hi @fanweiya, thank you for reporting the issue.
The error is caused when you have multiple GPU devices.
I will fix it in the next release. In the meantime, please try limiting the available GPU device in launching the server.

```
CUDA_VISIBLE_DEVICES=0 uvicorn cellsparse_api.main:app
```
