### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by abadgerw** [ksugar/qupath-extension-cellsparse#6]
I got everything installed and downloaded. I created training annotations (foreground and background) and ran training for a cellpose model through the cellsparse extension but received the following error:

ERROR: QuPath exception: pos < flushedPos!
java.lang.IndexOutOfBoundsException: pos < flushedPos!
    at java.desktop/javax.imageio.stream.ImageInputStreamImpl.seek(Unknown Source)
    at java.desktop/com.sun.imageio.plugins.png.IDATOutputStream.finishChunk(Unknown Source)
    at java.desktop/com.sun.imageio.plugins.png.IDATOutputStream.deflate(Unknown Source)
    at java.desktop/com.sun.imageio.plugins.png.IDATOutputStream.finish(Unknown Source)
    at java.desktop/com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(Unknown Source)
    at java.desktop/com.sun.imageio.plugins.png.PNGImageWriter.write(Unknown Source)
    at java.desktop/javax.imageio.ImageWriter.write(Unknown Source)
    at java.desktop/javax.imageio.ImageIO.doWrite(Unknown Source)
    at java.desktop/javax.imageio.ImageIO.write(Unknown Source)
    at org.elephant.cellsparse.AbstractCellsparseCommands.base64Encode(AbstractCellsparseCommands.java:37)
    at org.elephant.cellsparse.AbstractCellsparseCommands.CellsparseCommand(AbstractCellsparseCommands.java:83)
    at org.elephant.cellsparse.CellsparseCellposeExtension$CellsparseCellposeCommands.lambda$new$0(CellsparseCellposeExtension.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createImageDataAction$0(QuPathGUI.java:387)
    at org.controlsfx.control.action.Action.handle(Action.java:423)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$2(GlobalMenuAdapter.java:153)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:234)

Do you happen to know where this is stemming from?

Thanks in advance for your help!

**Comment by abadgerw** [comment]
@ksugar I also tested with stardist via cellsparse and got the same error as above.

**Comment by ksugar** [comment]
Hi @abadgerw, thank you for reporting the issue. Could you provide me with some information to investigate it further?
- Size of the input image (Width x Height)
- Number of channels of the input image
- Number of annotations
Thanks!
